### ISSUE TITLE
Query syntax results in CompileError with "undefined function"

### ISSUE THREAD

**Issue by jec** [dominique-vassard/seraph#14]
I updated my repo at https://github.com/jec/my_app to include a test case with a Seraph query:

_test/my_app/auth/user_test.exs:_

```elixir
#...
result = match([{u, User}])
|> where([u.identifier == "phred" and u.password == "foobar"])
|> return([u])
|> MyApp.Repo.one()
#...
```

This outputs the following warnings and error:

```
warning: variable "u" does not exist and is being expanded to "u()", please use parentheses to remove the ambiguity or change the variable name
  test/my_app/auth/user_test.exs:28: MyApp.Auth.UserTest."test can query for a User node"/1

warning: variable "u" does not exist and is being expanded to "u()", please use parentheses to remove the ambiguity or change the variable name
  test/my_app/auth/user_test.exs:28: MyApp.Auth.UserTest."test can query for a User node"/1

warning: variable "created_user" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/my_app/auth/user_test.exs:25: MyApp.Auth.UserTest."test can query for a User node"/1

warning: variable "result" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/my_app/auth/user_test.exs:27: MyApp.Auth.UserTest."test can query for a User node"/1


== Compilation error in file test/my_app/auth/user_test.exs ==
** (CompileError) test/my_app/auth/user_test.exs:28: undefined function u/0
    (elixir 1.11.3) src/elixir_locals.erl:114: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:416: Kernel.ParallelCompiler.require_file/2
    (elixir 1.11.3) lib/kernel/parallel_compiler.ex:316: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I notice in Seraph's project settings that it's using elixir >= 1.8. Are newer versions of elixir (I'm using 1.11.3 as seen above) more strict on parsing things like the bare "u" in the above code?

**Comment by dominique-vassard** [comment]
It seems that this is only a doc mislead.
```elixir
result = match([{u, User}])
|> where(u.identifier == "phred" and u.password == "foobar")
|> return([u])
|> MyApp.Repo.one()
```
works (without the square brackets).

And it's the same with the keyword syntax
```elixir
query =
      match [{u, User}],
        where: u.identifier == "phred" and u.password == "foobar",
        return: [u]

MyApp.Repo.all(query)
```

**Comment by dominique-vassard** [comment]
Doc is updated

**Comment by jec** [comment]
Yep, that works. Thanks!
